export const fortunes = [
  "You will have a great day!",
  "Success is in your future.",
  "Adventure is calling you.",
  "Happiness is around the corner.",
  "You will discover something wonderful.",
  "An unexpected gift will come your way.",
  "Your hard work will soon pay off.",
  "Someone will surprise you with kindness.",
  "A new opportunity is on the horizon.",
  "Good news will brighten your day.",
  "You are about to achieve your goals.",
  "A smile is your key to success today.",
  "You will make a valuable connection.",
  "Creativity will bring you rewards.",
  "An exciting journey awaits you.",
  "You are stronger than you think.",
  "A small act of kindness will return tenfold.",
  "Luck is on your side this week.",
  "A new friendship will enrich your life.",
  "Your positive attitude will inspire others.",
  "Take a chance; fortune favors the bold.",
  "Your dreams are closer than they seem.",
  "Someone is thinking highly of you right now.",
  "A long-awaited change is coming your way.",
  "You will find clarity in a difficult decision.",
  "Your patience will be rewarded soon.",
  "You are destined for greatness.",
  "A new hobby will bring you joy.",
  "Trust your instincts; they will guide you well.",
  "This is the start of something amazing."
];